-- Data Source Operational DB Schema
-- Tables mirror the synthetic data models generated by offline_data_gen.py

CREATE TABLE IF NOT EXISTS users (
    user_id           BIGINT      PRIMARY KEY,
    age               INTEGER,
    subscription_type TEXT,
    signup_ts         TIMESTAMPTZ,
    gender            TEXT                        -- NULL for pre-schema-evolution records
);

CREATE TABLE IF NOT EXISTS movies (
    movie_id         BIGINT      PRIMARY KEY,
    genre            TEXT,
    country          TEXT,
    runtime_seconds  INTEGER,
    language         TEXT,
    release_year     INTEGER,
    created_at       TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS playbacks (
    playback_id              BIGINT          PRIMARY KEY,
    user_id                  BIGINT,
    movie_id                 BIGINT,
    click_ts                 TIMESTAMPTZ,
    start_ts                 TIMESTAMPTZ,
    completion_rate          DOUBLE PRECISION,
    duration_watched_seconds INTEGER,
    end_ts                   TIMESTAMPTZ,
    playback_date            TEXT
);

CREATE TABLE IF NOT EXISTS ratings (
    rating_id   BIGINT      PRIMARY KEY,
    user_id     BIGINT,
    movie_id    BIGINT,
    rating      INTEGER,
    rating_ts   TIMESTAMPTZ,
    rating_date TEXT
);

CREATE TABLE IF NOT EXISTS payments (
    payment_id     BIGINT           PRIMARY KEY,
    user_id        BIGINT,
    payment_method TEXT,
    currency       TEXT,
    payment_status TEXT,
    payment_ts     TIMESTAMPTZ,
    amount         DOUBLE PRECISION,
    payment_date   TEXT
);
